name: Deploy Portfolio
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.HOST_SECRET}}
          username: ubuntu
          key: ${{secrets.SSH_KEY}}
          script: |
           set -e  # <-- This stops the script immediately if ANY command fails!
            cd ~/projects/portfolio_website
            git fetch origin main
            git reset --hard origin/main  # <-- Forces the server to match GitHub exactly
            docker stop portfolio || true
            docker rm portfolio || true
            docker build --no-cache -t portfolio .  # <-- Prevents Docker from using old cache
            docker run -d -p 80:5000 --name portfolio portfolio